
name: Pull request 

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check pull request
        run: |
          echo github.head_ref
          echo github.base_ref
          echo github.head_ref != 'dev'
          echo github.base_ref = 'prod'
          echo [ github.head_ref != 'dev' && github.base_ref = 'prod' ]
          if [[ github.head_ref != 'dev' && github.base_ref = 'prod' ]]; then
            echo "Pull requests into prod branch must be made from the dev branch"
            exit 1
          else
            echo "Pull request is valid"
            exit 0
          fi