
name: Pull request 

on:
  pull_request:

jobs:
  build:
    if:  ${{ github.base_ref == 'prod' && github.head_ref != 'dev' }} 
    runs-on: ubuntu-latest
    steps:
      - name: Check pull request
        run: |
            echo "Pull requests into prod branch must be made from the dev branch"
            exit 1
          